### ISSUE TITLE
drawer: make keyboard accessible

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/classic-design-system#1959]
### Expected behavior

Keyboard nav to toggle open

### Actual behavior

Can't keyboard nav (example code sandbox https://codesandbox.io/s/codesandboxer-example-forked-x2zu4?file=/package.json)

Source: https://pluralsight.slack.com/archives/C70HPSJPP/p1628603932011600

**Comment by caseybaggz** [comment]
No longer adding features to this project. Closing.
