### ISSUE TITLE
codesandbox>axios dependency update

### ISSUE THREAD

**Issue by Rykus0** [pluralsight/classic-design-system#2080]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When codesandbox has [updated its axios dependency](https://github.com/codesandbox/codesandbox-importers/issues/136), and then [remark-codesandbox](https://github.com/kevin940726/remark-codesandbox) upgraded to include that dependency, update our gatsby-remark-inline-codesandbox dependency.

[PR to bump axios from 0.18.1 to 0.21.1](https://github.com/codesandbox/codesandbox-importers/pull/101)

**Comment by Rykus0** [comment]
This may no longer be necessary, with the change to dependency organization

**Comment by caseybaggz** [comment]
No longer adding features to this project. Closing.
