### ISSUE TITLE
[Bug?]: Broken aria reference in Dropdown Component.

### ISSUE THREAD

**Issue by charlene-gilbert** [pluralsight/classic-design-system#2141]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Using [WAVE](https://wave.webaim.org/), it detects a broken aria reference error for the Dropdown component. The `aria-labelledby` component contains a reference to an id that doesn't get rendered in the component.

``` html
<div class="psds-dropdown"><label><span class="psds-dropdown__label psds-theme--light">Search by</span></label><div class="psds-dropdown__field-container"><div class="psds-halo psds-theme--light psds-halo--shape-default psds-halo--gap-size-small psds-halo--visible-on-focus psds-dropdown__field-halo"><div class="psds-dropdown__field-aligner"><button aria-labelledby="dropdown-button-ntmcn3xd5 dropdown-label-7qpy16a6c" id="dropdown-button-ntmcn3xd5" aria-haspopup="listbox" aria-expanded="false" class="psds-dropdown__field psds-dropdown__field--appearance-default psds-theme--light"><span class="psds-dropdown__field-inner"><span aria-hidden="true" class="psds-dropdown__button-sizer">Market Taxonomy Concept</span><span class="psds-dropdown__placeholder">Title</span></span><div class="psds-dropdown__icon psds-dropdown__icon--appearance-default psds-theme--light"><span class="psds-icon psds-icon--size-medium"><svg role="img" aria-label="caret down icon" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M11.6464 15.0565L7.35354 10.7636C7.15828 10.5683 7.15828 10.2518 7.35354 10.0565L8.05692 9.35311C8.25199 9.15804 8.5682 9.15782 8.76354 9.35262L12 12.5801L15.2364 9.35262C15.4318 9.15782 15.748 9.15804 15.943 9.35311L16.6464 10.0565C16.8417 10.2518 16.8417 10.5683 16.6464 10.7636L12.3535 15.0565C12.1583 15.2518 11.8417 15.2518 11.6464 15.0565Z"></path></svg></span></div></button></div></div></div></div>
```

specific aria-labelledby 
`<button aria-labelledby="dropdown-button-ntmcn3xd5 dropdown-label-7qpy16a6c" id="dropdown-button-ntmcn3xd5"`

`dropdown-label-7qpy16a6c` does not exist. I have tested with and without the `label` attribute set and the generated id does not exist.

### Expected behavior 🤔

labelId should be rendered somewhere in the component or it should be removed from aria-labelledby. 

### Steps to reproduce 🕹

Steps:

1. Navigate to [Tag Assignments](https://app.pluralsight.com/assignments/?)
2. Using [WAVE](https://wave.webaim.org/) browser extension scan page
3. Observe accessibility errors

### Context 🔦

Trying to complete PluralSIGHT Day tasks by resolving WAVE errors on oru page.

### Your environment 🌎

```shell
Firefox 107.0.1 (64-bit)
on Windows 10 Pro
```

**Comment by Rykus0** [comment]
Sorry for the delay, @charlene-gilbert.  It looks like the component is not correctly configured, and it is missing a label.  If you want the label to be visually hidden, you can [hide it so it is still accessible](https://www.a11yproject.com/posts/how-to-hide-content/).

If this isn't enough, or I'm misunderstanding, please let me know.

**Comment by Rykus0** [comment]
Looking at this again, I see that the label's ID is not assigned to the label, so the labelledby attribute is not correctly configured.
